targets:
  $default:
    sources:
      - $package$
      - "lib/**"
      - "node/**" # main.dart MUST be in node folder.
      # - "test/**"
    builders:
      build_node_compilers|entrypoint:
        options:
          compiler: dart2js # To compile with dart2js by default
          dart2js_args:
            - --no-minify
            - --enable-asserts
